### ISSUE TITLE
import errors for tsfresh modules

### ISSUE THREAD

**Issue by inferno9004** [blue-yonder/tsfresh#291]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system - OSX (yosemite), python 2.7 anaconda dist
2. The version of *tsfresh* that you are using - (current)
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one) - module import error
4. A minimal code snippet which reproduces the problem/bug

```
from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import make_forecasting_frame
from tsfresh.utilities.dataframe_functions import impute

```
ERROR STACK - 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-58e9e9f20edf> in <module>()
      4 import seaborn as sns
      5 
----> 6 from tsfresh import extract_features
      7 from tsfresh.utilities.dataframe_functions import make_forecasting_frame
      8 from sklearn.ensemble import AdaBoostRegressor

/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/__init__.py in <module>()
     31 
     32 
---> 33 from tsfresh.convenience.relevant_extraction import extract_relevant_features
     34 from tsfresh.feature_extraction import extract_features
     35 from tsfresh.feature_selection import select_features

/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/convenience/relevant_extraction.py in <module>()
      5 from __future__ import absolute_import
      6 import pandas as pd
----> 7 from tsfresh.feature_extraction import extract_features
      8 from tsfresh import defaults
      9 from tsfresh.feature_selection import select_features

/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/feature_extraction/__init__.py in <module>()
      3 """
      4 
----> 5 from tsfresh.feature_extraction.extraction import extract_features
      6 from tsfresh.feature_extraction.settings import ComprehensiveFCParameters, MinimalFCParameters, \
      7     EfficientFCParameters

/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py in <module>()
     18 from tqdm import tqdm
     19 
---> 20 from tsfresh import defaults
     21 from tsfresh.feature_extraction import feature_calculators
     22 from tsfresh.feature_extraction.settings import ComprehensiveFCParameters

ImportError: cannot import name defaults

```

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by MaxBenChrist** [comment]
Can you please paste the result of a `pip freeze`here?

**Comment by inferno9004** [comment]
```
pip freeze

alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.3.1
appnope==0.1.0
appscript==1.0.1
argcomplete==1.0.0
astroid==1.4.7
astropy==1.2.1
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.1.0
cdecimal==2.3
cffi==1.7.0
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
conda==4.3.23
conda-build==2.0.2
configobj==5.0.6
configparser==3.5.0
contextlib2==0.5.3
cryptography==1.5
cycler==0.10.0
Cython==0.24.1
cytoolz==0.8.0
dask==0.11.0
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
docutils==0.12
dynd==0.7.3.dev1
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.0.5
gevent==1.1.2
greenlet==0.4.10
grin==1.2.1
h5py==2.6.0
HeapDict==1.0.0
idna==2.1
imagesize==0.7.1
imbalanced-learn==0.2.1
ipaddress==1.0.16
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
lazy-object-proxy==1.2.1
llvmlite==0.13.0
locket==0.2.0
lxml==3.6.4
MarkupSafe==0.23
matplotlib==1.5.3
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.8
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.3.0
numba==0.28.1+0.gfe99fbc.dirty
numexpr==2.6.1
numpy==1.12.1
odo==0.5.0
openpyxl==2.3.2
pandas==0.20.3
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pep8==1.7.0
pexpect==4.0.1
pickleshare==0.7.4
Pillow==3.3.1
pkginfo==1.3.2
ply==3.9
prompt-toolkit==1.0.3
psutil==4.3.1
ptyprocess==0.5.1
py==1.4.31
pyasn1==0.1.9
PyAudio==0.2.7
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.3.0
Pygments==2.1.3
pylint==1.5.4
pyOpenSSL==16.2.0
pyparsing==2.1.4
pystan==2.15.0.1
pytest==2.9.2
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
pyzmq==15.4.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.1.2
redis==2.10.5
requests==2.14.2
rope==0.9.4
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.19.0
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.4.6
SQLAlchemy==1.0.13
statsmodels==0.6.1
sympy==1.0
tables==3.2.3.1
terminado==0.6
toolz==0.8.0
tornado==4.4.1
tqdm==4.15.0
traitlets==4.3.0
tsfresh==0.9.0
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.11.11
widgetsnbextension==1.2.6
wrapt==1.10.6
xlrd==1.0.0
XlsxWriter==0.9.3
xlwings==0.10.0
xlwt==1.1.2
```
```

pip install tsfresh

Requirement already satisfied: tsfresh in /Users/aamir/anaconda/lib/python2.7/site-packages
Requirement already satisfied: six>=1.10.0 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: future>=0.16.0 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: numpy>=1.10.4 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: tqdm>=4.10.0 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: requests>=2.9.1 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: scikit-learn>=0.17.1 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: scipy>=0.17.0 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: pandas>=0.20.3 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: patsy>=0.4.1 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: statsmodels>=0.6.1 in /Users/aamir/anaconda/lib/python2.7/site-packages (from tsfresh)
Requirement already satisfied: pytz>=2011k in /Users/aamir/anaconda/lib/python2.7/site-packages (from pandas>=0.20.3->tsfresh)
Requirement already satisfied: python-dateutil in /Users/aamir/anaconda/lib/python2.7/site-packages (from pandas>=0.20.3->tsfresh)
```

**Comment by MaxBenChrist** [comment]
I cannot reproduce the bug on my side. 

Can you poste the used chain of conda commands which you used to install tsfresh?

**Comment by inferno9004** [comment]
from the notebook itself -
cell 1 -
```

%matplotlib inline
!pip install tsfresh

```
### tsfresh was installed
no errors up until now.

cell 2 -

```
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns

from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import make_forecasting_frame
from sklearn.ensemble import AdaBoostRegressor
from tsfresh.utilities.dataframe_functions import impute

import pandas_datareader.data as web
import datetime

import warnings
warnings.filterwarnings('ignore')
```

this gave the error stack mentioned above.

I also restarted everything, re installed tsfresh from terminal. 
same error.

I restarted the laptop.
same error.

**Comment by inferno9004** [comment]
basically, I am trying to replicate your code - https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_google_stock.ipynb

**Comment by MaxBenChrist** [comment]
Have you tried to load the package inside a normal python and not the ipython interpreter?

So just so 

`python` 

and then 

`from tsfresh import extract_features`

**Comment by inferno9004** [comment]
```
$ python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pandas as pd
>>> from tsfresh import extract_features
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/__init__.py", line 33, in <module>
    from tsfresh.convenience.relevant_extraction import extract_relevant_features
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/convenience/relevant_extraction.py", line 7, in <module>
    from tsfresh.feature_extraction import extract_features
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/feature_extraction/__init__.py", line 5, in <module>
    from tsfresh.feature_extraction.extraction import extract_features
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 21, in <module>
    from tsfresh.feature_extraction import feature_calculators
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 25, in <module>
    from statsmodels.tsa.ar_model import AR
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 8, in <module>
    from statsmodels.regression.linear_model import OLS
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/statsmodels/regression/__init__.py", line 1, in <module>
    from .linear_model import yule_walker
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/statsmodels/regression/linear_model.py", line 52, in <module>
    import statsmodels.base.model as base
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/statsmodels/base/model.py", line 5, in <module>
    from statsmodels.base.data import handle_data
  File "/Users/aamir/anaconda/lib/python2.7/site-packages/statsmodels/base/data.py", line 8, in <module>
    from pandas import DataFrame, Series, TimeSeries, isnull
ImportError: cannot import name TimeSeries
>>> 

```

**Comment by MaxBenChrist** [comment]
Now it cannot import the statsmodel package. It feels like somehow your anaconda environment is broken. I have not used anaconda so far, have to read into that.

**Comment by inferno9004** [comment]
Alright, I will probably try to reinstall anaconda.
The note book I am replicating is anaconda too.

**Comment by inferno9004** [comment]
Hi..

I was trying to install tsfresh via command line on a windows machine this time. This also has the anaconda distribution. Something happens with the existing pandas library. 

Below is the error stack -
```

>pip install tsfresh
Collecting tsfresh
  Downloading tsfresh-0.9.0-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 696kB/s
Requirement already satisfied: six>=1.10.0 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: scipy>=0.17.0 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: future>=0.16.0 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: requests>=2.9.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Collecting pandas>=0.20.3 (from tsfresh)
  Downloading pandas-0.20.3-cp27-cp27m-win_amd64.whl (8.3MB)
    100% |################################| 8.3MB 139kB/s
Requirement already satisfied: numpy>=1.10.4 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: patsy>=0.4.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: scikit-learn>=0.17.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: statsmodels>=0.6.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Collecting tqdm>=4.10.0 (from tsfresh)
  Downloading tqdm-4.15.0-py2.py3-none-any.whl (46kB)
    100% |################################| 51kB 4.3MB/s
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda2\lib\site-packages (from pandas>=0.20.3->tsfresh)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda2\lib\site-packages (from pandas>=0.20.3->tsfresh)
Installing collected packages: pandas, tqdm, tsfresh
  Found existing installation: pandas 0.20.1
    Uninstalling pandas-0.20.1:
Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\req\req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pip\utils\__init__.py", line 267, in renames
    shutil.move(old, new)
  File "C:\ProgramData\Anaconda2\lib\shutil.py", line 300, in move
    rmtree(src)
  File "C:\ProgramData\Anaconda2\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\ProgramData\Anaconda2\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\ProgramData\Anaconda2\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\ProgramData\Anaconda2\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: 'c:\\programdata\\anaconda2\\lib\\site-packages\\pandas\\api\\types\\__init__.py'

C:\Users\aamir>python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pandas as pd
>>> import tsfresh as ts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tsfresh
>>>
```

**Comment by nils-braun** [comment]
I think the line `Access is denied: 'c:\\programdata\\anaconda2\\lib\\site-packages\\pandas\\api\\types\\__init__.py'` does not sound so good. This has nothing to do with `tsfresh`, but with your local python setup.

**Comment by inferno9004** [comment]
Although you have already closed it..

I ran cmd as admin and it worked on Windows...
I will test on mac as well..but over there it was not an issue with access permissions (as you can see from the above comments.).

Thanks

```

>pip install tsfresh
Collecting tsfresh
  Using cached tsfresh-0.9.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: scipy>=0.17.0 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: future>=0.16.0 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: requests>=2.9.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Collecting pandas>=0.20.3 (from tsfresh)
  Using cached pandas-0.20.3-cp27-cp27m-win_amd64.whl
Requirement already satisfied: numpy>=1.10.4 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: patsy>=0.4.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: scikit-learn>=0.17.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Requirement already satisfied: statsmodels>=0.6.1 in c:\programdata\anaconda2\lib\site-packages (from tsfresh)
Collecting tqdm>=4.10.0 (from tsfresh)
  Using cached tqdm-4.15.0-py2.py3-none-any.whl
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda2\lib\site-packages (from pandas>=0.20.3->tsfresh)
Requirement already satisfied: python-dateutil in c:\programdata\anaconda2\lib\site-packages (from pandas>=0.20.3->tsfresh)
Installing collected packages: pandas, tqdm, tsfresh
  Found existing installation: pandas 0.20.1
    Uninstalling pandas-0.20.1:
      Successfully uninstalled pandas-0.20.1
Successfully installed pandas-0.20.3 tqdm-4.15.0 tsfresh-0.9.0

C:\Windows\system32>python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tsfresh as ts
C:\ProgramData\Anaconda2\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
>>> from tsfresh import extract_features
```

**Comment by MaxBenChrist** [comment]
I think that in the Mac case the problem was that you installed tsfresh with pip, using a anaconda environment. See 

https://conda.io/docs/using/pkgs.html#install-non-conda-packages

Have you activated the conda environment before installing tsfresh?

**Comment by MaxBenChrist** [comment]
Have you tried installing any other package in the mac case? Just do the same thing you did with tsfresh in the python notebook with another package, I am certain that it will also fail.

**Comment by nils-braun** [comment]
You could test a `pip install -U tsfresh` if you like

**Comment by hanhanwu** [comment]
I had to run `conda install -c conda-forge tsfresh` to install, then the import error resolved....
