### ISSUE TITLE
KeyboardInterrupt not working

### ISSUE THREAD

**Issue by nikhase** [blue-yonder/tsfresh#302]
I use tsfresh in my experiment. I am running several `extract_features` calls inside a for loop. I am currently on the master branch. The same behaviour is present in V `0.10.0` and `0.9.0`. OS: Ubuntu 16.04, Python `2.7.13`.

Seems like the often used `Ctrl+C` does not work to interrupt:

```
^CProcess PoolWorker-1:
Traceback (most recent call last):
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-4:
Traceback (most recent call last):
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    self.run()
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/pool.py", line 113, in worker
Process PoolWorker-3:
Traceback (most recent call last):
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    result = (True, func(*args, **kwds))
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 291, in _do_extraction_on_chunk
    result = (True, func(*args, **kwds))
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 291, in _do_extraction_on_chunk
    self.run()
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/process.py", line 114, in run
    return list(_f())
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 278, in _f
    self._target(*self._args, **self._kwargs)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/pool.py", line 113, in worker
    result = func(data, param=parameter_list)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1581, in agg_linear_trend
    return list(_f())
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 285, in _f
    for key, item in result:
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 281, in <genexpr>
    result = ((convert_to_output_format(param), func(data, **param)) for param in parameter_list)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 912, in number_cwt_peaks
    result = (True, func(*args, **kwds))
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/multiprocessing/pool.py", line 65, in mapstar
    return map(*args)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 291, in _do_extraction_on_chunk
    return list(_f())
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 278, in _f
    result = func(data, param=parameter_list)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 363, in augmented_dickey_fuller
    aggregate_result = _aggregate_on_chunks(x, f_agg, chunk_len)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 120, in _aggregate_on_chunks
    return [getattr(x[i * chunk_len: (i + 1) * chunk_len], f_agg)() for i in range(int(np.ceil(len(x) / chunk_len)))]
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/numpy/core/_methods.py", line 102, in _var
    return len(find_peaks_cwt(vector=x, widths=np.array(list(range(1, n + 1))), wavelet=ricker))
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/scipy/signal/_peak_finding.py", line 517, in find_peaks_cwt
    arrmean = umr_sum(arr, axis, dtype, keepdims=True)
KeyboardInterrupt
    ridge_lines = _identify_ridge_lines(cwt_dat, max_distances, gap_thresh)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/scipy/signal/_peak_finding.py", line 320, in _identify_ridge_lines
    diffs = np.abs(col - prev_ridge_cols)
KeyboardInterrupt
    res = adfuller(x)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/statsmodels/tsa/stattools.py", line 240, in adfuller
    maxlag, autolag)
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/statsmodels/tsa/stattools.py", line 86, in _autolag
    results[lag] = mod_instance.fit()
  File "/home/niklas/anaconda3/envs/py27masterthesis/lib/python2.7/site-packages/statsmodels/regression/linear_model.py", line 198, in fit
    beta = np.dot(self.pinv_wexog, self.wendog)
KeyboardInterrupt
```

Seems like this is a well-known problem:

* [SO:keyboard-interrupts-with-pythons-multiprocessing-pool](https://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool)
* [SO: catch-ctrlc-sigint-and-exit-multiprocesses-gracefully-in-python](https://stackoverflow.com/questions/11312525/catch-ctrlc-sigint-and-exit-multiprocesses-gracefully-in-python)

**Comment by nikhaas** [comment]
[This SO answer](https://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool#answer-44869451) worked for me. I inserted into `extraction.py`:

```python
[...]
def init_worker():
    signal.signal(signal.SIGINT, signal.SIG_IGN)

[...]
def _do_extraction(df, column_id, column_value, column_kind,
                   default_fc_parameters, kind_to_fc_parameters,
                   n_jobs, chunksize, disable_progressbar):
[...]
    if n_jobs == 0:
        map_function = map
    else:
        pool = Pool(n_jobs, init_worker)
```
But the `KeyboardInterrupt` takes some time to be recognised. I also inserted ne `except`, which might be necessary. I do not think "my" solution to be good practice.

One might need to adapt `relevance.py` as well.

**Comment by MaxBenChrist** [comment]
Valid issue, thanks for reporting it.

We/ I will have to Recherche this topic.

I am interested how sklearn etc. are solving this

**Comment by MaxBenChrist** [comment]
Okay. I read into the issue. 

See also https://stackoverflow.com/questions/34473069/multiprocessing-keyboardinterrupt-handling

Insights:

- not catching the keyboard interrupt is a bug in python 2
- This is solved for python3. So, the current version of tsfresh will catch the KeyBoardInterrupt properly in python3.
- One needs a hacky solution to get it done right on python2. 

I happily review any pr that solves this but I will not actively look for a solution here. I think the gains in userfriendlyness are negligible compared to the costs of maintaining this.

**Comment by nils-braun** [comment]
As it is solved in python 3 and we will soon drop python 2 support, we can also close this.
