### ISSUE TITLE
Value error significance tests

### ISSUE THREAD

**Issue by pabucur** [blue-yonder/tsfresh#340]
Hi,

I got a value error during feature selection, significance tests.
```
File "C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_selection\significance_tests.py", line 114, in target_binary_feature_real_test
    y0, y1 = y.unique()
ValueError: not enough values to unpack (expected 2, got 1)
```

Info.
1. Windows 7 64 Bit
2. tsfresh 0.11.0
3. The Dataframe contains 10 examples. There is an ID Column, a time Column and two timeseries with length 751 each, with values ranging between 60 and 130. The dataframe is created from a numpy array
```
    for i in range(0, len(test_input)):
        block = test_input[i]
        for j in range(0, len(block[0])):
            d_test.append({'ID': i, 'Time': j, 'TS_5': block[4, j], 'TS_10': block[9, j]})
        if i == 10:
            break
```
4. `test_features = extract_relevant_features(test_input, test_labels, column_id='ID', column_sort='Time')`
5.
```
 Feature Extraction:   0%|          | 0/11 [00:00<?, ?it/s]C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py:897: RuntimeWarning: invalid value encountered in power
  return y.dot(np.arange(len(y))**moment) / y.sum()
C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py:897: RuntimeWarning: invalid value encountered in power
  return y.dot(np.arange(len(y))**moment) / y.sum()
C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py:897: RuntimeWarning: invalid value encountered in power
  return y.dot(np.arange(len(y))**moment) / y.sum()
C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py:897: RuntimeWarning: invalid value encountered in power
  return y.dot(np.arange(len(y))**moment) / y.sum()
Feature Extraction: 100%|██████████| 11/11 [00:14<00:00,  1.29s/it]
WARNING:tsfresh.feature_selection.relevance:Infered classification as machine learning task
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_selection\significance_tests.py", line 114, in target_binary_feature_real_test
    y0, y1 = y.unique()
ValueError: not enough values to unpack (expected 2, got 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "M:/Github Projects/KGT-Analyse/TRUNK/SixSigmaKGT/Network/Cockpit.py", line 60, in <module>
    test_features = extract_relevant_features(test_input, test_labels, column_id='ID', column_sort='Time')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\convenience\relevant_extraction.py", line 153, in extract_relevant_features
    ml_task=ml_task)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_selection\selection.py", line 142, in select_features
    fdr_level=fdr_level, hypotheses_independent=hypotheses_independent,
  File "C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_selection\relevance.py", line 161, in calculate_relevance_table
    fdr_level, map_function
  File "C:\ProgramData\Anaconda3\lib\site-packages\tsfresh\feature_selection\relevance.py", line 190, in _calculate_relevance_table_for_implicit_target
    map_function(test_real_feature, [X[feature] for feature in table_real.index]),
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
ValueError: not enough values to unpack (expected 2, got 1)
```

What is causing this problem?

**Comment by pabucur** [comment]
Found the error: I was testing tsfresh and did it only on a small data subset, which all had the same label. This lead to the exception. If I choose another subset with both labels the exception does not occur.

**Comment by MaxBenChrist** [comment]
We could add a more verbose error if only one label is passed to the selection, I think I saw issues with this error before.

**Comment by nils-braun** [comment]
PR was merged.

**Comment by Quneker** [comment]
In this Value Error, there is a step which calculate y0, y1 = y.unique()，you can check this function by y0,y1=test_labels.unique(), it maynot work. If so ,you can try add test_labels.dropna(inplace=True) before function extract_relevant_features().
