### ISSUE TITLE
Broken documentation build - `python setup.py docs` fails during the first call 

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#349]
Currently our documentation on Read-the-docs is broken.

What is really weird is that when I, on a clean repository call `python setup.py docs` the build fails with the following trace

```
Installed /Users/max/Documents/tsfresh/.eggs/PyScaffold-2.5.8-py2.7.egg
[pbr] Generating ChangeLog
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/max/Documents/tsfresh/.eggs/PyScaffold-2.5.8-py2.7.egg/pyscaffold/contrib/pbr/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/max/Documents/tsfresh/.eggs/PyScaffold-2.5.8-py2.7.egg/pyscaffold/contrib/pbr/pbr/util.py", line 267, in cfg_to_args
    wrap_commands(kwargs)
  File "/Users/max/Documents/tsfresh/.eggs/PyScaffold-2.5.8-py2.7.egg/pyscaffold/contrib/pbr/pbr/util.py", line 569, in wrap_commands
    cmdclass = ep.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/sphinx/setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/sphinx/application.py", line 33, in <module>
    from sphinx.environment import BuildEnvironment
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/sphinx/environment/__init__.py", line 46, in <module>
    from sphinx.util.websupport import is_commentable
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/sphinx/util/websupport.py", line 11, in <module>
    from sphinxcontrib.websupport.utils import is_commentable  # NOQA
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/sphinxcontrib/websupport/__init__.py", line 15, in <module>
    from sphinxcontrib.websupport.core import WebSupport  # NOQA
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/sphinxcontrib/websupport/core.py", line 17, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
    MutableMapping.register(LRUCache)
  File "/Users/max/Documents/tsfresh/venv/bin/../lib/python2.7/abc.py", line 109, in register
    if issubclass(subclass, cls):
  File "/Users/max/Documents/tsfresh/venv/bin/../lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/Users/max/Documents/tsfresh/venv/lib/python2.7/site-packages/typing.py", line 1265, in __subclasscheck__
    return super(GenericMeta, self).__subclasscheck__(cls)
TypeError: super() argument 1 must be type, not None
error in setup command: Error parsing /Users/max/Documents/tsfresh/setup.cfg: TypeError: super() argument 1 must be type, not None
```

Afterwards, a second call to `python setup.py docs` builds the documentation...

This error is similiar to the reports here
https://github.com/hasura/docs/issues/148 
and here
https://github.com/sphinx-doc/sphinx/issues/3976

Downgrading sphinx to 1.5.6 shows similiar problems with a first call to `python setup.py docs` failing, with another error trace.

**Comment by MaxBenChrist** [comment]
Vanished with updating to newer versions
