### ISSUE TITLE
non initiated MinimalFCParameters dictionary in pipeline_with_two_datasets.ipynb

### ISSUE THREAD

**Issue by bmmalone** [blue-yonder/tsfresh#358]
1. Your operating system

Ubuntu 16.04

2. The version of *tsfresh* that you are using

0.11.0

3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)

Example data is in minimal example below. Interestingly, though, the problem doesn't happen when the MinimalFCParameters flag is not given.

4. A minimal code snippet which reproduces the problem/bug

```
import pandas as pd
from tsfresh import extract_features
from tsfresh.feature_extraction.settings import MinimalFCParameters

time = [0,1,2, 0,1,2, 0,1,2, 0,1,2]
kind = ["A","A","A", "B","B","B", "A","A","A", "B","B","B"]
value = [5,10,15, 5,10,15, 5,10,15, 5,10,15]
identifier = ["C","C","C","C","C","C", "D","D","D", "D","D","D"]

cols = {
    "time": time,
    "kind": kind,
    "value": value,
    "id": identifier
}

df = pd.DataFrame(cols)

X = extract_features(
    timeseries_container=df,
    column_id='id',
    column_sort='time',
    column_kind="kind",
    column_value="value",
    default_fc_parameters=MinimalFCParameters
)
```

5. Any reported errors or traceback

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 

Traceback (most recent call last):
  File "/home/bmalone/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/bmalone/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 38, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/home/bmalone/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 37, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/home/bmalone/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 293, in _do_extraction_on_chunk
    return list(_f())
  File "/home/bmalone/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 276, in _f
    for function_name, parameter_list in fc_parameters.items():
TypeError: descriptor 'items' of 'dict' object needs an argument


The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-39-e4da67ec5b73> in <module>()
     22     column_kind="kind",
     23     column_value="value",
---> 24     default_fc_parameters=MinimalFCParameters
     25 )

~/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor)
    150                                 default_fc_parameters=default_fc_parameters,
    151                                 kind_to_fc_parameters=kind_to_fc_parameters,
--> 152                                 distributor=distributor)
    153 
    154         # Impute the result if requested

~/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py in _do_extraction(df, column_id, column_value, column_kind, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, distributor)
    231     kwargs = dict(default_fc_parameters=default_fc_parameters, kind_to_fc_parameters=kind_to_fc_parameters)
    232     result = distributor.map_reduce(_do_extraction_on_chunk, data=data_in_chunks, chunk_size=chunk_size,
--> 233                                     function_kwargs=kwargs)
    234     distributor.close()
    235 

~/.virtualenvs/digital-health/lib/python3.6/site-packages/tsfresh/utilities/distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    147             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    148 
--> 149         result = list(itertools.chain.from_iterable(result))
    150 
    151         return result

~/.virtualenvs/digital-health/lib/python3.6/site-packages/tqdm/_tqdm.py in __iter__(self)
    870 """, fp_write=getattr(self.fp, 'write', sys.stderr.write))
    871 
--> 872             for obj in iterable:
    873                 yield obj
    874                 # Update and print the progressbar.

~/local/lib/python3.6/multiprocessing/pool.py in next(self, timeout)
    697         if success:
    698             return value
--> 699         raise value
    700 
    701     __next__ = next                    # XXX

TypeError: descriptor 'items' of 'dict' object needs an argument
```
Edit: missing import for `MinimalFCParameters`

**Comment by MaxBenChrist** [comment]
You have to instantiate the MinimalFCParameters dictionary. 

``` Python
X = extract_features(
    timeseries_container=df,
    column_id='id',
    column_sort='time',
    column_kind="kind",
    column_value="value",
    default_fc_parameters=MinimalFCParameters()
)
```
should do the job

**Comment by bmmalone** [comment]
Thanks, that was the problem.

By chance, the line in the `pipeline_with_two_datasets.ipynb` notebook which specifies the parameters (in Cell 4) breaks such that the parenthesis are on a line by themselves.  I think that's how I missed them the first time.

I find this package very helpful for collecting all of the different features normally extracted for time series. The feature filtering also seems reasonable. Thanks for making it available.

**Comment by MaxBenChrist** [comment]
> By chance, the line in the pipeline_with_two_datasets.ipynb notebook which specifies the parameters (in Cell 4) breaks such that the parenthesis are on a line by themselves. I think that's how I missed them the first time.

thanks for reporting, we will correct that

**Comment by nils-braun** [comment]
As far as I can see the layout problem is gone.
