### ISSUE TITLE
OverflowError: value too large to convert to int

### ISSUE THREAD

**Issue by sethmachine** [blue-yonder/tsfresh#368]
Edit: I reduced the CSV file to 10 million rows (now ~3 GB) simply by using "head" command and feature extraction progress bar has shown up.  I don't think it's a memory problem, because I am using 128 GB of RAM and was nowhere close to capping out with the original 26 GB CSV.  I think the problem is that very large dataframes aren't being handled correctly, or some assumption is made about their size.  

Edit2: Ran into another memory error with the above data.  

```
Feature Extraction:   0%|          | 0/70 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/foobar/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/foobar/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 38, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/foobar/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 37, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 293, in _do_extraction_on_chunk
    return list(_f())
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 287, in _f
    for key, item in result:
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 283, in <genexpr>
    result = ((convert_to_output_format(param), func(data, **param)) for param in parameter_list)
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1610, in approximate_entropy
    return np.abs(_phi(m) - _phi(m + 1))
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1606, in _phi
    C = np.sum(np.max(np.abs(x_re[:, np.newaxis] - x_re[np.newaxis, :]),
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tsfresh_extractor_cli.py", line 88, in <module>
    main()
  File "tsfresh_extractor_cli.py", line 78, in main
    te.select_features(outfile, fdr_level=args.fdr_level)
  File "/foobar/tsfresh_extractor.py", line 123, in select_features
    features = self.extract_features(overwrite)
  File "/foobar/tsfresh_extractor.py", line 82, in extract_features
    features = tsfresh.extract_features(self.timeseries_data, column_id='guid', column_sort='frameIndex')
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 152, in extract_features
    distributor=distributor)
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 233, in _do_extraction
    function_kwargs=kwargs)
  File "/foobar/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 149, in map_reduce
    result = list(itertools.chain.from_iterable(result))
  File "/foobar/lib/python3.6/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/foobar/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
MemoryError
```

1. Your operating system

Red Hat Linux

2. The version of *tsfresh* that you are using

latest pull from "pip install tsfresh"
tsfresh==0.11.0

3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)

26 GB CSV file with 32 columns each float64, except ID column which is an integer.  72,520,390 rows (many rows are just timesteps of a single timeseries since they have the same column ID).  

I have successfully run feature extractions on the same exact CSV, just many fewer rows (in the MB, not GB).  So I don't think it's how the dataframe is structured.  

4. A minimal code snippet which reproduces the problem/bug

Calling "tsfresh.extract_features" on the dataframe created from the above CSV file.  

5. Any reported errors or traceback

```
2018-03-21 20:48:00,095 INFO:Tsfresh_Extractor Loading time series data
2018-03-21 20:53:55,687 INFO:Tsfresh_Extractor Loading time series targets
2018-03-21 20:53:55,690 INFO:Tsfresh_Extractor Extracting features from tfresh
Traceback (most recent call last):
  File "tsfresh_extractor_cli.py", line 88, in <module>
    main()
  File "tsfresh_extractor_cli.py", line 78, in main
    te.select_features(outfile, fdr_level=args.fdr_level)
  File "/foobar/tsfresh_extractor.py", line 123, in select_features
    features = self.extract_features(overwrite)
  File "/foobar/tsfresh_extractor.py", line 82, in extract_features
    features = tsfresh.extract_features(self.timeseries_data, column_id='guid', column_sort='frameIndex')
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 152, in extract_features
    distributor=distributor)
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 217, in _do_extraction
    data_in_chunks = [x + (y,) for x, y in df.groupby([column_id, column_kind])[column_value]]
  File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 217, in <listcomp>
    data_in_chunks = [x + (y,) for x, y in df.groupby([column_id, column_kind])[column_value]]
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 1833, in get_iterator
    splitter = self._get_splitter(data, axis=axis)
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 1839, in _get_splitter
    comp_ids, _, ngroups = self.group_info
  File "pandas/_libs/properties.pyx", line 38, in pandas._libs.properties.cache_readonly.__get__
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 1951, in group_info
    comp_ids, obs_group_ids = self._get_compressed_labels()
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 1967, in _get_compressed_labels
    all_labels = [ping.labels for ping in self.groupings]
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 1967, in <listcomp>
    all_labels = [ping.labels for ping in self.groupings]
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 2658, in labels
    self._make_labels()
  File "/foobar/lib/python3.6/site-packages/pandas/core/groupby.py", line 2675, in _make_labels
    self.grouper, sort=self.sort)
  File "/foobar/lib/python3.6/site-packages/pandas/core/algorithms.py", line 468, in factorize
    table = hash_klass(size_hint or len(values))
  File "pandas/_libs/hashtable_class_helper.pxi", line 1005, in pandas._libs.hashtable.StringHashTable.__init__
OverflowError: value too large to convert to int
```

**Comment by earthgecko** [comment]
Hi @sethmachine I am not a contributor to tsfresh, just a user so everything here is pure conjecture, just a hunch.  I am sure that @MaxBenChrist or some one else may given you a much more concise answer, some please read theirs below first, if there are any.  I just found this intriguing.

You say that you do not think it's how the dataframe is structured, however to verify that you can post the DataFrame summary (str(df)) as well as a sample of the data (df.head()), however my hunch is it is in the numbers themselves.

It seems that a couple of people have run into a similar issue with pandas in the past and with big data sets too, by the looks of things.  If it has run before and has run successfully on this CSV data only smaller, then it suggests the data set more be the issue, but it could be related to something in tsfresh in it's ```_phi``` in ```approximate_entropy``` (see below)

But this is the pandas issue somewhat related to your original report, pre edits - https://github.com/pandas-dev/pandas/issues/2773

So in 26GB of CSV there may be something that is not an int or float64, perhaps.  And even in a  3GB file as.  Still perhaps not but no harm checking.

There could be another possibility as well in that in some instance of your problems, this may be related to some Python internals in multiprocessing itself, in terms of the number of objects, but that is really just a hunch.

From 

```
File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 283, in
result = ((convert_to_output_format(param), func(data, **param)) for param in parameter_list)
File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1610, in approximate_entropy
return np.abs(_phi(m) - _phi(m + 1))
File "/foobar/lib/python3.6/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1606, in _phi
C = np.sum(np.max(np.abs(x_re[:, np.newaxis] - x_re[np.newaxis, :]),
MemoryError
```
I have a hunch that something in the data set itself or maybe something to do with the 

>     For short time-series this method is highly dependent on the parameters,  but should be stable for N > 2000, see:

https://github.com/blue-yonder/tsfresh/blob/3f01c60d95985c76005f37018fee0d4fb605e72d/tsfresh/feature_extraction/feature_calculators.py#L1607

In the ```approximate_entropy``` function itself, as that comes out of ```def _phi```, surprising there is no ```np.phi``` there, is there even one?  Not hiding in plain sight it seems.

It is something related do with the above is my guess.  The only thing I can suggest is exclude approximate_entropy as a feature.

**Comment by MaxBenChrist** [comment]
sorry for the late response @sethmachine,

From your memory it looks like your calculation runs out of memory. You probably have a lot of cores on your machine right?

There are two ways to fix this

1. don't load all time series at once. You can iterate over your 26gb csv (pandas `read_csv` can return an iterator with a defined chunk size). I always extract features for 500mb to 1 gb chunks, this  also makes sure that I don't loose results if the caculation crashes
2. use the `LocalDaskDistributor` instead of the `MultiprocessingDistributor`. Dask should have a better memory footprint than the default multiprocessing library 
http://tsfresh.readthedocs.io/en/latest/text/tsfresh_on_a_cluster.html

I hope this helps

**Comment by MaxBenChrist** [comment]
@sethmachine, can you please post the output of 

```Python
import pandas as pd
pd.show_versions()
```

**Comment by soulmachine** [comment]
I have the same issue.

pd.show_versions():

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.5.3.final.0
python-bits: 64
OS: Linux
OS-release: 4.9.0-8-amd64
machine: x86_64
processor: 
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.23.4
pytest: None
pip: None
setuptools: 40.6.2
Cython: None
numpy: 1.15.1
scipy: 1.1.0
pyarrow: 0.11.1
xarray: None
IPython: 7.2.0
sphinx: None
patsy: None
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: None
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999999999
sqlalchemy: None
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
```

df.info():
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49707579 entries, 0 to 49707578
Data columns (total 2 columns):
drawing    object
y          int64
dtypes: int64(1), object(1)
memory usage: 758.5+ MB
```

**Comment by nils-braun** [comment]
It seems this issue is stalled. Closing it.
