### ISSUE TITLE
Breaking tests require dask local_dir

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#371]
1. operating system
Ubuntu 14.04.5 LTS

2. The version of *tsfresh*
v0.11.0

3. Problem setup test fails

```
../bin/python2.7 setup.py test
```
 tests are failing and they are failing on Travis too (https://travis-ci.org/blue-yonder/tsfresh/jobs/356811605#L1201)

```
[gw0] FAILED tests/units/utilities/test_distribution.py::LocalDaskDistributorTestCase::test_local_dask_cluster_extraction 
```

4. A minimal code snippet which reproduces the problem/bug - NONE
5. Any reported errors or traceback

```
=========================================================================================================== FAILURES ===========================================================================================================
_______________________________________________________________________________ LocalDaskDistributorTestCase.test_local_dask_cluster_extraction ________________________________________________________________________________
[gw0] linux2 -- Python 2.7.14 /opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/../bin/python2.7

self = <tests.units.utilities.test_distribution.LocalDaskDistributorTestCase testMethod=test_local_dask_cluster_extraction>

    def test_local_dask_cluster_extraction(self):

>       Distributor = LocalDaskDistributor(n_workers=1)

/opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/tests/units/utilities/test_distribution.py:50:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/tsfresh/utilities/distribution.py:238: in __init__
    cluster = LocalCluster(n_workers=n_workers, processes=False)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/deploy/local.py:127: in __init__
    self.start(ip=ip, n_workers=n_workers)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/deploy/local.py:145: in start
    sync(self.loop, self._start, **kwargs)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/utils.py:254: in sync
    six.reraise(*error[0])
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/utils.py:238: in f
    result[0] = yield make_coro()
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py:1107: in run
    yielded = self.gen.throw(*exc_info)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/deploy/local.py:163: in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py:1099: in run
    value = future.result()
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py:849: in callback
    result_list.append(f.result())
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/concurrent.py:260: in result
    raise_exc_info(self._exc_info)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py:315: in wrapper
    yielded = next(result)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/deploy/local.py:179: in _start_worker
    silence_logs=self.silence_logs, **kwargs)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/worker.py:1139: in __init__
    WorkerBase.__init__(self, *args, **kwargs)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/worker.py:115: in __init__
    self._workspace = WorkSpace(local_dir)
/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/diskutils.py:110: in __init__
    self.base_dir = os.path.abspath(base_dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'dask-worker-space'

    def abspath(path):
        """Return an absolute path."""
        if not isabs(path):
            if isinstance(path, _unicode):
                cwd = os.getcwdu()
            else:
>               cwd = os.getcwd()
E               OSError: [Errno 2] No such file or directory

/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/posixpath.py:364: OSError
----------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------
distributed.utils - ERROR - [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/deploy/local.py", line 163, in _start
    yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py", line 849, in callback
    result_list.append(f.result())
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
    raise_exc_info(self._exc_info)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/deploy/local.py", line 179, in _start_worker
    silence_logs=self.silence_logs, **kwargs)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/worker.py", line 1139, in __init__
    WorkerBase.__init__(self, *args, **kwargs)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/worker.py", line 115, in __init__
    self._workspace = WorkSpace(local_dir)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/lib/python2.7/site-packages/distributed/diskutils.py", line 110, in __init__
    self.base_dir = os.path.abspath(base_dir)
  File "/opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/../lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
```

This is fixed with passing the ```local_dir``` parameter to LocalDaskDistributor via tempfile (preferable to hard coded /tmp dir say)

```
        import tempfile
        self.test_dir = tempfile.mkdtemp()
        worker_kwargs = {'n_workers': n_workers, 'processes': False, 'local_dir': self.test_dir}
        cluster = LocalCluster(**worker_kwargs)
```

PR incoming

**Comment by earthgecko** [comment]
Fixes test_local_dask_cluster_extraction on Travis

```[gw0] [ 88%] PASSED tests/units/utilities/test_distribution.py::LocalDaskDistributorTestCase::test_local_dask_cluster_extraction
```
https://travis-ci.org/blue-yonder/tsfresh/jobs/356867648#L1267

**Comment by MaxBenChrist** [comment]
Awesome @earthgecko! This was bugging me. The weird thing is, the test suite only failed the first time you execute it. The second time, this error does not occur anymore.

**Comment by earthgecko** [comment]
## Also fixing notebook test timeouts

On Travis some notebook tests are timing out on the default ```"--ExecutePreprocessor.timeout=600"]```

https://github.com/blue-yonder/tsfresh/blob/6db60f46e3587540b81d7b0187dc46047e40a15e/tests/integrations/test_notebooks.py#L25
 
As described in per PR #372 (see links to tests with timeout).   This can be resolved by adding longer timeouts to tsfresh/tests/integrations/test_notebooks.py

Although not ideal to bundle all these changes in one PR, however to get the tests to pass ... :)

**Comment by MaxBenChrist** [comment]
We fixed this on master, thanks @earthgecko
