### ISSUE TITLE
select_features Error

### ISSUE THREAD

**Issue by vahidnadi** [blue-yonder/tsfresh#397]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. OS : windows 8.1
2. tsfresh version 0.11.0
3. data: 
          [TaggedID.zip](https://github.com/blue-yonder/tsfresh/files/2219253/TaggedID.zip)
           [LastTags.zip](https://github.com/blue-yonder/tsfresh/files/2219224/LastTags.zip)
4. code:
        timeseries=pd.read_csv('E:/Nahieh9/Data/timeseries/TaggedID.csv')
        timeseries = timeseries[['id','date','reactive','active']]
        tags=pd.read_csv('E:/Nahieh9/Data/Tags/LastTags.csv')
        y = pd.Series(tags['takhalof'].values, index=tags['id'])
        y_train,y_test =train_test_split(y)
        timeseries_train = timeseries.loc[timeseries.id.isin(y_train.index)]   
        timeseries_test = timeseries.loc[timeseries.id.isin(y_test.index)]
        X_train = pd.DataFrame(index=y_train.index)
        X_test = pd.DataFrame(index=y_test.index)
        if __name__ == '__main__':    
                extracted_features = extract_features(timeseries_train,column_id='id',column_sort='date')
                impute(extracted_features)
                features_filtered  = select_features(extracted_features,y_train)

5.  traceback
WARNING:tsfresh.feature_selection.relevance:Infered classification as machine learning task
Traceback (most recent call last):
  File "c:\Users\vahid-laptop\Desktop\Final\Classify Time Series\tsfresh\tmp3.py", line 37, in <module>
    column_id='id', column_sort='date')
  File "C:\Users\vahid-laptop\AppData\Local\Programs\Python\Python36\lib\site-packages\tsfresh\convenience\relevant_extraction.py", line 153, in extract_relevant_features
    ml_task=ml_task)
  File "C:\Users\vahid-laptop\AppData\Local\Programs\Python\Python36\lib\site-packages\tsfresh\feature_selection\selection.py", line 144, in select_features
    fdr_level=fdr_level, hypotheses_independent=hypotheses_independent,
  File "C:\Users\vahid-laptop\AppData\Local\Programs\Python\Python36\lib\site-packages\tsfresh\feature_selection\relevance.py", line 161, in calculate_relevance_table
    fdr_level, map_function
  File "C:\Users\vahid-laptop\AppData\Local\Programs\Python\Python36\lib\site-packages\tsfresh\feature_selection\relevance.py", line 190, in _calculate_relevance_table_for_implicit_target
    map_function(test_real_feature, [X[feature] for feature in table_real.index]),
  File "C:\Users\vahid-laptop\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\vahid-laptop\AppData\Local\Programs\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
ValueError: cannot reindex from a duplicate axis

**Comment by earthgecko** [comment]
Hi @vahidnadi unfortunately the above zip files are are not working for me as the appear not to be valid zip files.

```bash

  $ unzip -t TaggedID.zip
  Archive:  TaggedID.zip
    End-of-central-directory signature not found.  Either this file is not
    a zipfile, or it constitutes one disk of a multi-part archive.  In the
    latter case the central directory and zipfile comment will be found on
    the last disk(s) of this archive.
  unzip:  cannot find zipfile directory in one of TaggedID.zip or
        TaggedID.zip.zip, and cannot find TaggedID.zip.ZIP, period.

```

**Comment by MaxBenChrist** [comment]
Couldn't open your data neither. Will close then
