### ISSUE TITLE
mutilprocess error 

### ISSUE THREAD

**Issue by meishuguo** [blue-yonder/tsfresh#458]
1. 16.04.4 LTS (GNU/Linux 4.4.0-117-generic x86_64)
2. tsfresh __verison__: '0.11.1'

def main():
    pool = multiprocessing.Pool(processes = 40)
    feature_result_tmp = []
    for x in json_list:
        feature_result_tmp.append(pool.apply_async(columbusJsonSDK, (config_file, x)))
    pool.close()
    pool.join()
    print('all process done')
    result = []
    for x in feature_result_tmp:
        result.append(x.get())
    feature_result = pd.concat(result, axis=0)

**In my program, I create a  multiprocessing.Pool in my main function, and I  use tsfresh extract_features function in my child process,that cause a problem as follows. But When I remove the multiprocessing.Pool and use single process to extract features ,the program goes well**

`Traceback (most recent call last):
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "columbusJson.py", line 65, in columbusJsonSDK
    timestamp_feature_df = getTimsStampFeaturesFromjson(configObj, jsonStr)
  File "/media/data/yuanguo/columbus/util/wrapFeature.py", line 297, in getTimsStampFeaturesFromjson
    stats_result, stats_columns = eval(func + "(df, cache)")
  File "<string>", line 1, in <module>
  File "/media/data/yuanguo/columbus/features/basicFeatures.py", line 1188, in getSubjectWordTimestampStatsV2
    stats_result, stats_columns = getTimestampStatsV2(keyWordTimestamp)
  File "/media/data/yuanguo/columbus/features/basicFeatures.py", line 1178, in getTimestampStatsV2
    extracted_features = extract_features(timeseries, column_id="id", column_sort="time")
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 159, in extract_features
    distributor=distributor)
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 233, in _do_extraction
    progressbar_title="Feature Extraction")
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 345, in __init__
    self.pool = Pool(processes=n_workers)
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "columbusJson.py", line 112, in <module>
    result.append(x.get())
  File "/media/data/jiahaochen/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AssertionError: daemonic processes are not allowed to have children
`

**Comment by delyanr** [comment]
Sounds like you are not allowed to spawn 'grand-children' from your Pool processes. The `extract_features()` method spawns two children by default (refer to the API documentation). Try passing `n_jobs=0` as an argument.

**Comment by meishuguo** [comment]
> Sounds like you are not allowed to spawn 'grand-children' from your Pool processes. The `extract_features()` method spawns two children by default (refer to the API documentation). Try passing `n_jobs=0` as an argument to the `extract_features()` method.

it works，thankyou
