### ISSUE TITLE
tsfresh ImportError: cannot import name defaults

### ISSUE THREAD

**Issue by antoinedarius** [blue-yonder/tsfresh#463]
I use Python 2.7.15 from Anaconda, and my OS is MacOS Mojave 10.14
I first dowloand tsfresh using: "conda install tsfresh" in my terminal.
Then in python, when running: "from tsfresh.feature_extraction import extract_features", I get the following error:
"from tsfresh.feature_extraction import extract_features
Traceback (most recent call last):

  File "<ipython-input-31-e60cd15644e4>", line 1, in <module>
    from tsfresh.feature_extraction import extract_features

  File "/Users/Antoine/anaconda2/lib/python2.7/site-packages/tsfresh/__init__.py", line 33, in <module>
    from tsfresh.convenience.relevant_extraction import extract_relevant_features

  File "/Users/Antoine/anaconda2/lib/python2.7/site-packages/tsfresh/convenience/relevant_extraction.py", line 7, in <module>
    from tsfresh.feature_extraction import extract_features

  File "/Users/Antoine/anaconda2/lib/python2.7/site-packages/tsfresh/feature_extraction/__init__.py", line 5, in <module>
    from tsfresh.feature_extraction.extraction import extract_features

  File "/Users/Antoine/anaconda2/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 16, in <module>
    from tsfresh import defaults

ImportError: cannot import name defaults"

Can you please advise?

Thanks for your help!

**Comment by MaxBenChrist** [comment]
Please update to 0.11.2 on conda/pip

**Comment by canerK** [comment]
Hi 

I just installed ts-fresh with conda

     **conda install -c conda-forge tsfresh**

the installed version is 0.11.2

     **tsfresh            conda-forge/noarch::tsfresh-0.11.2-py_0**

after the installation receiving an error when I try to df.head() ( the df is the pandas dataframe)

**ImportError                               Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)**

/caner
