### ISSUE TITLE
OSError: [Errno 22]

### ISSUE THREAD

**Issue by acmilannesta** [blue-yonder/tsfresh#533]
Hi, 

I'm running tsfresh 0.11.2 on win10 in python 3.6.8. When I test the sample codes I got the following error:

```
from tsfresh import extract_relevant_features, extract_features
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, load_robot_execution_failures
if __name__ == '__main__':
    download_robot_execution_failures()
    timeseries, y = load_robot_execution_failures()
    features_filtered_direct = extract_features(timeseries, column_id='id', column_sort='time')
```

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Python 3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Python 3.6\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Python 3.6\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Python 3.6\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Python 3.6\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "E:\Python 3.6\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'Z:\\Zhensheng Wang\\Julien\\Adult readmission\\<input>'

**Comment by MaxBenChrist** [comment]
Did you try to run it without multi-processing? (`n_jobs=1`)

**Comment by acmilannesta** [comment]
> Did you try to run it without multi-processing? (`n_jobs=0`) . From the stacktrace, it does not look like the error stems from tsfresh but from the python multiprocessing library

Yes, I tried. But still the same error.
