### ISSUE TITLE
struct.error: (Struct Overflow) while Feature Extraction

### ISSUE THREAD

**Issue by Infatum** [blue-yonder/tsfresh#613]
Feature Extraction:   0%|                                                                                                              | 0/40 [00:00<?, ?it/s]
Process ForkPoolWorker-3:                                                         
Traceback (most recent call last):                                                
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker           
    put((job, i, result))                                                          
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put        
    self._writer.send_bytes(obj)                                     
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)                                              
struct.error: 'i' format requires -2147483648 <= number <= 2147483647  
                                                                       
During handling of the above exception, another exception occurred:               
                                                                        
Traceback (most recent call last):                                                 
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()                                                       
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run           
    self._target(*self._args, **self._kwargs)                      
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 130, in worker           
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put        
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])                           
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)                                              
struct.error: 'i' format requires -2147483648 <= number <= 2147483647  
Process ForkPoolWorker-2:                                                         
Traceback (most recent call last):                                                
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker           
    put((job, i, result))                                                          
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put

**Comment by nils-braun** [comment]
It is very hard to solve this issue without any context, but I guess it looks more like a multiprocessing error/problem than a tsfresh one. 

That said, the multiprocessing has some known limitations but it is very very hard to reason about in your case if there is not a bit more context.

**Comment by dbarbier** [comment]
This issue can be closed IMHO.
