### ISSUE TITLE
Empty result of extract_features 

### ISSUE THREAD

**Issue by damomeen** [blue-yonder/tsfresh#644]
I preparing unsupervised ML solution and would like to use tsfresh to prepare features for PCA. I have a problem because `extract_features` function provides very frequently an empty result (see point 5 below). I have reduced the dataset to demonstrate the problem. Why do I see the empty result of `extract_features` ? 

1. Ubuntu 18.04.4 LTS
2. tsfresh version: 0.14.1
3. My minimalistic dataframe is: 
```
df

   id  value
0   0   2078
1   0   2079
2   0   2091
3   0   2074
4   0   2081
5   0   2086
6   0   2092
7   0   2081
8   0   2068
9   0   2094
```
4. I try extract features using:
```python
from tsfresh.feature_extraction.settings import EfficientFCParameters, ComprehensiveFCParameters, MinimalFCParameters
extracted_features = extract_features(df, n_jobs=0, column_id="id", kind_to_fc_parameters=MinimalFCParameters())  
print(extracted_features)
```
5. Code output is:
```
Feature Extraction: 100%|██████████| 1/1 [00:00<00:00, 16.54it/s]
Empty DataFrame
Columns: []
Index: []
```

**Comment by damomeen** [comment]
I have been able to get feature calculations from data after hacking your `_do_extraction_on_chunk` function. Some feature calculations have raised exceptions so I have caught them in order to continue `for` loop them and get results from other calculation functions.
```
from tsfresh.feature_extraction import feature_calculators
from tsfresh.utilities.string_manipulation import convert_to_output_format
import traceback

data =  df
rs = []
for function_name, parameter_list in EfficientFCParameters().items():
    #print(function_name, parameter_list)
    func = getattr(feature_calculators, function_name)
    if getattr(func, 'input', False) == 'pd.Series':
        # If it has a required index type, check that the data has the right index type.
        index_type = getattr(func, 'index_type', None)
        if index_type is not None:
            try:
                assert isinstance(data.index, index_type)
            except AssertionError:
                warnings.warn(
                    "{} requires the data to have a index of type {}. Results will "
                    "not be calculated".format(function_name, index_type)
                )
                continue
        x = data
    else:
        x = data.values

    if func.fctype == "combiner":
        try:
            result = func(x, param=parameter_list)
        except Exception:
            print(function_name, parameter_list)
            traceback.print_exc()
            result = [("", 0)]
    else:
        if parameter_list:
            result = []
            for param in parameter_list:
                try:
                    value = func(x, **param)
                except Exception:
                    print(function_name, parameter_list)
                    traceback.print_exc()
                    value = 0
                result.append((convert_to_output_format(param), value))
        else:
            try:
                result = [("", func(x))]
            except Exception:
                print(function_name, parameter_list)
                traceback.print_exc()
                result = [("", 0)]

    for key, item in result:
        feature_name = func.__name__
        if key:
            feature_name += "__" + str(key)
        rs.append({"variable": feature_name, "value": item})
print(rs)
```

There is a list of exceptions I get:
```
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 46, in <module>
    result = [("", func(x))]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 484, in abs_energy
    return np.dot(x, x)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (10,2) and (10,2) not aligned: 2 (dim 1) != 10 (dim 0)
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 46, in <module>
    result = [("", func(x))]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 661, in skewness
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 46, in <module>
    result = [("", func(x))]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 678, in kurtosis
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 46, in <module>
    result = [("", func(x))]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 711, in longest_strike_below_mean
    return np.max(_get_length_sequences_where(x < np.mean(x))) if x.size > 0 else 0
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 106, in _get_length_sequences_where
    res = [len(list(group)) for value, group in itertools.groupby(x) if value == 1]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 106, in <listcomp>
    res = [len(list(group)) for value, group in itertools.groupby(x) if value == 1]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 46, in <module>
    result = [("", func(x))]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 726, in longest_strike_above_mean
    return np.max(_get_length_sequences_where(x > np.mean(x))) if x.size > 0 else 0
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 106, in _get_length_sequences_where
    res = [len(list(group)) for value, group in itertools.groupby(x) if value == 1]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 106, in <listcomp>
    res = [len(list(group)) for value, group in itertools.groupby(x) if value == 1]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 46, in <module>
    result = [("", func(x))]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 864, in percentage_of_reoccurring_values_to_all_values
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 521, in cid_ce
    return np.sqrt(np.dot(x, x))
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (10,1) and (10,1) not aligned: 1 (dim 1) != 10 (dim 0)
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 521, in cid_ce
    return np.sqrt(np.dot(x, x))
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (10,1) and (10,1) not aligned: 1 (dim 1) != 10 (dim 0)
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1596, in quantile
    x = pd.Series(x)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 202, in __init__
    if is_empty_data(data) and dtype is None:
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/construction.py", line 586, in is_empty_data
    is_simple_empty = is_list_like_without_dtype and not data
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 1479, in __nonzero__
    f"The truth value of a {type(self).__name__} is ambiguous. "
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 28, in <module>
    result = func(x, param=parameter_list)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 364, in agg_autocorrelation
    a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/stattools.py", line 575, in acf
    x = array_like(x, 'x')
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/statsmodels/tools/validation/validation.py", line 136, in array_like
    raise ValueError(msg.format(name, ndim, arr.ndim))
ValueError: x is required to have ndim 1 but has ndim 2
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 28, in <module>
    result = func(x, param=parameter_list)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 415, in partial_autocorrelation
    pacf_coeffs = list(pacf(x, method="ld", nlags=max_lag))
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/stattools.py", line 867, in pacf
    acv = acovf(x, unbiased=True, fft=False)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/stattools.py", line 375, in acovf
    x = array_like(x, 'x', ndim=1)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/statsmodels/tools/validation/validation.py", line 136, in array_like
    raise ValueError(msg.format(name, ndim, arr.ndim))
ValueError: x is required to have ndim 1 but has ndim 2
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1165, in number_cwt_peaks
    return len(find_peaks_cwt(vector=x, widths=np.array(list(range(1, n + 1))), wavelet=ricker))
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/_peak_finding.py", line 1292, in find_peaks_cwt
    cwt_dat = cwt(vector, wavelet, widths)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/wavelets.py", line 472, in cwt
    output[ind] = convolve(data, wavelet_data, mode='same')
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 1273, in convolve
    raise ValueError("volume and kernel should have the same "
ValueError: volume and kernel should have the same dimensionality
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1165, in number_cwt_peaks
    return len(find_peaks_cwt(vector=x, widths=np.array(list(range(1, n + 1))), wavelet=ricker))
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/_peak_finding.py", line 1292, in find_peaks_cwt
    cwt_dat = cwt(vector, wavelet, widths)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/wavelets.py", line 472, in cwt
    output[ind] = convolve(data, wavelet_data, mode='same')
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 1273, in convolve
    raise ValueError("volume and kernel should have the same "
ValueError: volume and kernel should have the same dimensionality
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 28, in <module>
    result = func(x, param=parameter_list)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1226, in cwt_coefficients
    calculated_cwt[widths] = cwt(x, ricker, widths)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/wavelets.py", line 472, in cwt
    output[ind] = convolve(data, wavelet_data, mode='same')
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/scipy/signal/signaltools.py", line 1273, in convolve
    raise ValueError("volume and kernel should have the same "
ValueError: volume and kernel should have the same dimensionality
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 28, in <module>
    result = func(x, param=parameter_list)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1078, in fft_aggregated
    res = [calculation[config["aggtype"]](fft_abs) for config in param]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1078, in <listcomp>
    res = [calculation[config["aggtype"]](fft_abs) for config in param]
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1015, in get_centroid
    return get_moment(y, 1)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1006, in get_moment
    return y.dot(np.arange(len(y), dtype=float)**moment) / y.sum()
ValueError: shapes (10,2) and (10,) not aligned: 2 (dim 1) != 10 (dim 0)
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 28, in <module>
    result = func(x, param=parameter_list)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1779, in friedrich_coefficients
    calculated[m][r] = _estimate_friedrich_coefficients(x, m, r)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 136, in _estimate_friedrich_coefficients
    df = pd.DataFrame({'signal': x[:-1], 'delta': np.diff(x)})
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
Traceback (most recent call last):
  File "<ipython-input-103-6918086babd5>", line 38, in <module>
    value = func(x, **param)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 1815, in max_langevin_fixed_point
    coeff = _estimate_friedrich_coefficients(x, m, r)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 136, in _estimate_friedrich_coefficients
    df = pd.DataFrame({'signal': x[:-1], 'delta': np.diff(x)})
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/home/dparniewicz/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
```

**Comment by damomeen** [comment]
Looking over above exceptions, I see following feature calculation methods that have raised exceptions:
```
abs_energy None
skewness None
kurtosis None
longest_strike_below_mean None
longest_strike_above_mean None
percentage_of_reoccurring_values_to_all_values None
cid_ce [{'normalize': True}, {'normalize': False}]
quantile [{'q': 0.1}, {'q': 0.2}, {'q': 0.3}, {'q': 0.4}, {'q': 0.6}, {'q': 0.7}, {'q': 0.8}, {'q': 0.9}]
agg_autocorrelation [{'f_agg': 'mean', 'maxlag': 40}, {'f_agg': 'median', 'maxlag': 40}, {'f_agg': 'var', 'maxlag': 40}]
partial_autocorrelation [{'lag': 0}, {'lag': 1}, {'lag': 2}, {'lag': 3}, {'lag': 4}, {'lag': 5}, {'lag': 6}, {'lag': 7}, {'lag': 8}, {'lag': 9}]
number_cwt_peaks [{'n': 1}, {'n': 5}]
cwt_coefficients [...]
fft_aggregated [{'aggtype': 'centroid'}, {'aggtype': 'variance'}, {'aggtype': 'skew'}, {'aggtype': 'kurtosis'}]
friedrich_coefficients [{'coeff': 0, 'm': 3, 'r': 30}, {'coeff': 1, 'm': 3, 'r': 30}, {'coeff': 2, 'm': 3, 'r': 30}, {'coeff': 3, 'm': 3, 'r': 30}]
max_langevin_fixed_point [{'m': 3, 'r': 30}]
linear_trend [{'attr': 'pvalue'}, {'attr': 'rvalue'}, {'attr': 'intercept'}, {'attr': 'slope'}, {'attr': 'stderr'}]
```

**Comment by nils-braun** [comment]
The reason why you are getting no features is that you are using `kind_to_fc_parameters` instead of using `default_fc_parameters=MinimalFCParameters()`. With that, you will get extracted features.

If you really want to use the kind_to_fc_parameters: It should be a mapping from your column names to the settings (so it should be `{"value": MinimalFCParameters()}` in your case).
