### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by demontamer** [blue-yonder/tsfresh#647]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system - Aws cluster
2. The version of *tsfresh* that you are using 
0.14
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
4. A minimal code snippet which reproduces the problem/bug
'X = extract_features(rolled,column_id="id", column_sort="time",column_kind="kind", column_value="price",
    default_fc_parameters=EfficientFCParameters(),distributor=Distributor) # n_jobs=8,chunksize=100)
' - i copied and paste from @nils-braun pdf Google example
'      price                 time                   id      kind
0  533334.0  2018-01-05 08:55:00  2018-01-06 04:34:00  
1   15266.0  2018-01-05 08:55:00  2018-01-06 04:34:00      open
2   15320.0  2018-01-05 08:55:00  2018-01-06 04:34:00      high
3   15266.0  2018-01-05 08:55:00  2018-01-06 04:34:00       low
4   15320.0  2018-01-05 08:55:00  2018-01-06 04:34:00     close
5. Any reported errors or traceback
Traceback (most recent call last):
  File "app/trading/mlbots/test/tsfresh_.py", line 173, in <module>
    X,Y = get_data(')
  File "app/test/tsfresh_.py", line 141, in get_data
    default_fc_parameters=EfficientFCParameters(),distributor=Distributor) # n_jobs=8,chunksize=100)
  File "/usr/local/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 160, in extract_features
    distributor=distributor)
  File "/usr/local/lib/python3.6/site-packages/tsfresh/feature_extraction/extraction.py", line 311, in _do_extraction
    function_kwargs=kwargs)
  File "/usr/local/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 153, in map_reduce
    chunk_size = self.calculate_best_chunk_size(data_length)
  File "/usr/local/lib/python3.6/site-packages/tsfresh/utilities/distribution.py", line 320, in calculate_best_chunk_size
    chunk_size, extra = divmod(data_length, n_workers * 5)
ZeroDivisionError: integer division or modulo by zero
'

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by demontamer** [comment]
The documentation has tsfresh only needs the address of scheduler? I hadn't created any workers so it makes sense that chuck_size raising above exception.
