### ISSUE TITLE
defining param's for feature calculators

### ISSUE THREAD

**Issue by leanindustry** [blue-yonder/tsfresh#652]
1. windows 10
2. The latest version of *tsfresh* 
3. pin = _temporary_index_column	y

0	19
18	19
1	36
17	36
2	51
16	51
3	64
15	64
4	75
14	75
5	84
13	84
6	91
12	91
7	96
11	96
8	99
10	99
9	100

4.
In[78]: param = {'f_agg':'mean','maxlag':40} 
In[79]: tsfresh.feature_extraction.feature_calculators.agg_autocorrelation(pin, param)

5. 

Traceback (most recent call last):

  File "<ipython-input-79-35f13f796faa>", line 1, in <module>
    tsfresh.feature_extraction.feature_calculators.agg_autocorrelation(pin, param)

  File "C:\Users\shawn.waltz\AppData\Local\Continuum\anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py", line 358, in agg_autocorrelation
    max_maxlag = max([config["maxlag"] for config in param])

  File "C:\Users\shawn.waltz\AppData\Local\Continuum\anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py", line 358, in <listcomp>
    max_maxlag = max([config["maxlag"] for config in param])

TypeError: string indices must be integers

Thanks

**Comment by nils-braun** [comment]
`param` must be a list of configurations, so 
```python
param = [{'f_agg':'mean','maxlag':40}]
```

Two comments:
* You can improve the readability of your issue by using the code formatting :-)
* Is there a particular reason you are using the raw feature calculators and not the convenience functions, e.g. `extract_features`?
