### ISSUE TITLE
tsfresh extract_features not working for AWS lambda

### ISSUE THREAD

**Issue by meghnaGlovo** [blue-yonder/tsfresh#657]
1. Your operating system - Amazon Linux
2. The version of *tsfresh* =0.15.1
3. data - I don't think its data-related issue, its OS related problem. 
4. Code
`courier_ts_features = extract_features(
        df_cour,
        column_id="courier_id",
        column_value=time_serie_column,
        column_sort="sending_time",
        impute_function=impute,
        show_warnings=False,
        disable_progressbar=False,
        default_fc_parameters=fc_parameters,
        n_jobs=1,
    )`
5. stacktrace
```
exception occurred:  <class 'OSError'>
Traceback (most recent call last):
File "/var/task/handler.py", line 56, in aggregate_and_publish
result = TimeToAcceptTransformer().execute(input_df)
File "/var/task/transformers/time_to_accept_transformer.py", line 25, in execute
df, self.get_aggregations(), "time_to_accept"
File "/var/task/transformers/time_to_accept_transformer.py", line 103, in extract_ts_features_primitive
n_jobs=1,
File "/tmp/sls-py-req/tsfresh/feature_extraction/extraction.py", line 160, in extract_features
distributor=distributor)
File "/tmp/sls-py-req/tsfresh/feature_extraction/extraction.py", line 301, in _do_extraction
show_warnings=show_warnings)
File "/tmp/sls-py-req/tsfresh/utilities/distribution.py", line 372, in __init__
self.pool = Pool(processes=n_workers, initializer=initialize_warnings_in_workers, initargs=(show_warnings,))
File "/var/lang/lib/python3.7/multiprocessing/context.py", line 119, in Pool
context=self.get_context())
File "/var/lang/lib/python3.7/multiprocessing/pool.py", line 158, in __init__
self._setup_queues()
File "/var/lang/lib/python3.7/multiprocessing/pool.py", line 251, in _setup_queues
self._inqueue = self._ctx.SimpleQueue()
File "/var/lang/lib/python3.7/multiprocessing/context.py", line 112, in SimpleQueue
return SimpleQueue(ctx=self.get_context())
File "/var/lang/lib/python3.7/multiprocessing/queues.py", line 332, in __init__
self._rlock = ctx.Lock()
File "/var/lang/lib/python3.7/multiprocessing/context.py", line 67, in Lock
return Lock(ctx=self.get_context())
File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
File "/var/lang/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
unlink_now)
OSError: [Errno 38] Function not implemented
```

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by nils-braun** [comment]
Thanks for the issue. 
I just tried to increase the readability of your post by adding proper code formatting. You can also do this by yourself the next time - it makes reading the debug printout much easier!

The error is not particularly `tsfresh` related. AWS Lambda can not run multiprocessing applications (as described e.g. in the documentation https://aws.amazon.com/de/blogs/compute/parallel-processing-in-python-with-aws-lambda/).
You can however just turn off multiprocessing of `tsfresh` by calling `extract_features` with the parameter `n_jobs=0` instead of `1`.

Also, make sure you really want to use AWS lambda for the feature extraction as you only have a small amount of time.
