### ISSUE TITLE
Got error when running distributed example in docs

### ISSUE THREAD

**Issue by hekaisheng** [blue-yonder/tsfresh#748]
The example(https://tsfresh.readthedocs.io/en/latest/text/tsfresh_on_a_cluster.html) run failed if statsmodels's version is v0.12.0.

``` Python
In [2]: import tsfresh                                                                              

In [3]: import statsmodels                                                                          

In [4]: tsfresh.__version__, statsmodels.__version__                                                
Out[4]: ('0.16.0', '0.12.0')

In [5]: from tsfresh.examples.robot_execution_failures import \ 
   ...:     download_robot_execution_failures, \ 
   ...:     load_robot_execution_failures 
   ...: from tsfresh.feature_extraction import extract_features 
   ...: from tsfresh.utilities.distribution import MultiprocessingDistributor 
   ...:  
   ...: # download and load some time series data 
   ...: download_robot_execution_failures() 
   ...: df, y = load_robot_execution_failures() 
   ...:  
   ...: # We construct a Distributor that will spawn the calculations 
   ...: # over four threads on the local machine 
   ...: Distributor = MultiprocessingDistributor(n_workers=4, 
   ...:                                          disable_progressbar=False, 
   ...:                                          progressbar_title="Feature Extraction") 
   ...:  
   ...: # just to pass the Distributor object to 
   ...: # the feature extraction, along the other parameters 
   ...: X = extract_features(timeseries_container=df, 
   ...:                      column_id='id', column_sort='time', 
   ...:                      distributor=Distributor)                                               
Feature Extraction:   0%|                                                    | 0/20 [00:00<?, ?it/s]/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:1577: RuntimeWarning: divide by zero encountered in log
  return -np.log(A / B)
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:367: FutureWarning: the 'unbiased'' keyword is deprecated, use 'adjusted' instead
  a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:367: FutureWarning: the 'unbiased'' keyword is deprecated, use 'adjusted' instead
  a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:1577: RuntimeWarning: invalid value encountered in long_scalars
  return -np.log(A / B)
Feature Extraction:   0%|                                                    | 0/20 [00:00<?, ?it/s]/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:367: FutureWarning: the 'unbiased'' keyword is deprecated, use 'adjusted' instead
  a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]

/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:367: FutureWarning: the 'unbiased'' keyword is deprecated, use 'adjusted' instead
  a = acf(x, unbiased=True, fft=n > THRESHOLD_TO_USE_FFT, nlags=max_maxlag)[1:]
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:1577: RuntimeWarning: divide by zero encountered in log
  return -np.log(A / B)
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:1577: RuntimeWarning: divide by zero encountered in log
  return -np.log(A / B)
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:1577: RuntimeWarning: divide by zero encountered in log
  return -np.log(A / B)
/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py:1577: RuntimeWarning: invalid value encountered in long_scalars
  return -np.log(A / B)
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 39, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 38, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 390, in _do_extraction_on_chunk
    return list(_f())
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 376, in _f
    result = func(x, param=parameter_list)
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 418, in partial_autocorrelation
    pacf_coeffs = list(pacf(x, method="ld", nlags=max_lag))
  File "/Users/hekaisheng/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/statsmodels/tsa/stattools.py", line 1026, in pacf
    "Can only compute partial correlations for lags up to 50% of the "
ValueError: Can only compute partial correlations for lags up to 50% of the sample size. The requested nlags 9 must be < 7.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-1-83ede963ea96> in <module>
     19 X = extract_features(timeseries_container=df,
     20                      column_id='id', column_sort='time',
---> 21                      distributor=Distributor)

~/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor)
    158                                 default_fc_parameters=default_fc_parameters,
    159                                 kind_to_fc_parameters=kind_to_fc_parameters,
--> 160                                 distributor=distributor)
    161 
    162         # Impute the result if requested

~/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py in _do_extraction(df, column_id, column_value, column_kind, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, show_warnings, distributor)
    309     result = distributor.map_reduce(_do_extraction_on_chunk, data=data_in_chunks,
    310                                     chunk_size=chunk_size,
--> 311                                     function_kwargs=kwargs)
    312     distributor.close()
    313 

~/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tsfresh/utilities/distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    165             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    166 
--> 167         result = list(itertools.chain.from_iterable(result))
    168 
    169         return result

~/miniconda3/envs/py3.7.2/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1128 
   1129         try:
-> 1130             for obj in iterable:
   1131                 yield obj
   1132                 # Update and possibly print the progressbar.

~/miniconda3/envs/py3.7.2/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

ValueError: Can only compute partial correlations for lags up to 50% of the sample size. The requested nlags 9 must be < 7.
```

**Comment by hekaisheng** [comment]
https://github.com/blue-yonder/tsfresh/blob/main/tsfresh/feature_extraction/feature_calculators.py#L447

the check here may modified to `n // 2 <= max_demanded_lag`.

**Comment by nils-braun** [comment]
Very good! Thanks for the issue 👍
Would you be willing to create a PR for your suggested change or shall I take care of it?
