### ISSUE TITLE
how can rolling_time_series deal with big data ?

### ISSUE THREAD

**Issue by lk1983823** [blue-yonder/tsfresh#771]
I have a 7m rows dataframe to deal with and want to use rolling_time_series in tsfresh. Whether using dask or not, I find it impossible to make it available. Because when using dask, inputs to the rolling_time_series function should using the form of df.compute(), thereby occupying a lot of memories during running. Are there any helpful suggestions ? Thanks!

**Comment by madpower2000** [comment]
The easiest way order compute instance with a lot of memory on Google cloud or AWS ;)

**Comment by lk1983823** [comment]
> The easiest way order compute instance with a lot of memory on Google cloud or AWS ;)
But I want to make it run in my machine.

**Comment by nils-braun** [comment]
What do you mean with the input needs df.compute()?

If you use dask as input to the rolling function, you can also hand over a non-evaluated dask data frame (not a pandas data frame). If you pass this directly to the extract features function, you in principle never need to go outside of dask.


However - of course - that is still a lot of data and I assume the feature extraction on 7M time series will also take a long time...

**Comment by lk1983823** [comment]
> What do you mean with the input needs df.compute()?
> 
> If you use dask as input to the rolling function, you can also hand over a non-evaluated dask data frame (not a pandas data frame). If you pass this directly to the extract features function, you in principle never need to go outside of dask.
> 
> However - of course - that is still a lot of data and I assume the feature extraction on 7M time series will also take a long time...
here is my code below:

```
windowSize = 100
dfSH05FillNan = dd.read_parquet('./testdf.parquet.gzip')
dfSH05FillNanDaskRolled = roll_time_series(dfSH05FillNan, 
                                              column_id="timeContinuity", column_sort="timestamp", chunksize=50,
                                              max_timeshift=windowSize-1, min_timeshift=windowSize-1)
```

it shows the error as follows:
```
Traceback (most recent call last):
  File "tsProcess.py", line 169, in <module>
    max_timeshift=windowSize-1, min_timeshift=windowSize-1)
  File "/home/lk/.pyenv/versions/anaconda3-2020.02/envs/ai/lib/python3.7/site-packages/tsfresh/utilities/dataframe_functions.py", line 576, in roll_time_series
    if df[column_sort].isnull().any():
  File "/home/lk/.pyenv/versions/anaconda3-2020.02/envs/ai/lib/python3.7/site-packages/dask/dataframe/core.py", line 199, in __bool__
    "a conditional statement.".format(self)
TypeError: Trying to convert dd.Scalar<series-..., dtype=bool> to a boolean value. Because Dask objects are lazily evaluated, they cannot be converted to a boolean value or used in boolean conditions like if statements. Try calling .compute() to force computation prior to converting to a boolean value or using in a conditional statement.
```
My tsfresh version is 0.16.0

**Comment by nils-braun** [comment]
Oh - I am very sorry. I somehow assumed #731 is already finished and implemented but have just remembered that this is not the case. 
Hm, well then you are completely correct - so far the rolling only accepts pandas data.

I think you can either wait for the PR to be finished (although it is kind of stuck currently) and/or help there - or you could try to do a staged approach where you roll only the first part of your data, then extract features and store it, then the second part... Maybe you can automate this with e.g. luigi.

If you want, I guess working on #731 would be very nice.

**Comment by arnabbiswas1** [comment]
Dask support for  `rolling_time_series()` will be highly appreciated. 

With larger than memory data, I assume following would be an ideal workflow:

1. Using Dask, read data for different `id`s (large number of CSVs or parquet files) stored in hard drive or cloud storage.
2. `rolling_time_series()` accepts a Dask DataFrame (source) and outputs the rolled data in another Dask DataFrame. This resultant Dask DataFrame, if computed will be larger than the source DataFrame. Hence, should be passed as it is (as Dask DataFrame without computation) to next step.
3. `dask_feature_extraction_on_chunk()` accepts the output from the previous step (in some shape and form). Computes the fetaures for different `id`s in the form of Dask DataFrame.
4. Features computed at step #3 can be stored back to the hard drive/cloud storage segregated based on `id`s. Or the Dask DataFrame from #3 can be passed as it is to Machine Learning libraries for training or prediction directly.

**Comment by vladjohnson** [comment]
+1 @arnabbiswas1 

Can we please get Dask support for rolling_time_series? Thanks!

**Comment by nils-braun** [comment]
Hi! 
I am happy for any contribution on this! If someone needs help getting started, feel free to reach out.

**Comment by hatahataDev** [comment]
I faced a similar problem when dealing with millions of rows of records. I dealt with this by using the above function that I created myself. I hope this helps.


```python
from tqdm.auto import tqdm
def fast_roll_time_series_with_tqdm(df: pd.DataFrame, column_id: str, column_sort: str, window_size: int) -> pd.DataFrame:
    """
    Efficient rolling window implementation with TQDM progress display.

    Parameters:
    -----------
    df : pandas.DataFrame
        Input DataFrame.
    column_id : str
        Column name for the time series ID.
    column_sort : str
        Column name for the time column to sort by.
    window_size : int
        Size of the rolling window.

    Returns:
    -------
    pandas.DataFrame
        DataFrame with rolling windows applied. Each row from the original df
        that could be the end of a window will result in `window_size` rows
        in the output, associated with a 'window_id'.
    """
    print("Starting rolling window processing...")

    # Check for NaN values in the sort column
    if df[column_sort].isnull().any():
        raise ValueError(f"NaN values found in the sort column '{column_sort}'. Please handle them before proceeding.")
    if not pd.api.types.is_numeric_dtype(df[column_sort]) and not pd.api.types.is_datetime64_any_dtype(df[column_sort]):
         print(f"Warning: Sort column '{column_sort}' is not numeric or datetime. Sorting might produce unexpected results if not comparable.")

    # Sort by time column within each ID group
    print(f"Sorting data by '{column_id}' and '{column_sort}'...")
    # Using reset_index(drop=True) is important for subsequent iloc operations
    df = df.sort_values([column_id, column_sort]).reset_index(drop=True)

    # Calculate the position (index) of each row within its group
    print("Calculating positions within groups...")
    # Using cumcount provides the 0-based index within each group
    df['_group_position'] = df.groupby(column_id).cumcount()

    # Determine if each row can be the end of a window (0-based index >= window_size - 1)
    print("Determining potential window end positions...")
    df['_is_window_end'] = df['_group_position'] >= (window_size - 1)

    # Filter only the rows that represent the end of a valid window
    window_ends_df = df[df['_is_window_end']].copy()
    num_windows = len(window_ends_df)
    print(f"Number of windows to generate: {num_windows}")

    if num_windows == 0:
        print("No valid windows could be generated with the given window size.")
        # Return an empty DataFrame with expected columns (or handle as needed)
        # Define expected columns based on original df + new ones
        expected_cols = list(df.columns) + ['window_id', f'{column_id}_original']
        # Remove temporary columns if they exist in the list
        expected_cols = [col for col in expected_cols if col not in ['_group_position', '_is_window_end']]
        return pd.DataFrame(columns=expected_cols)


    # Assign a unique ID to each window
    # This ID will link all rows belonging to the same window
    window_ends_df['window_id'] = np.arange(num_windows)

    # List to store the resulting window DataFrames before concatenation
    result_dataframes = []

    # --- Optimized Window Expansion ---
    print("Expanding windows...")

    # Pre-calculate group start indices for faster lookups
    group_indices = df.groupby(column_id).indices

    # Iterate through the rows that mark the end of each window
    for _, end_row in tqdm(window_ends_df.iterrows(), total=num_windows, desc="Expanding windows"):
        current_id = end_row[column_id]
        end_position_in_group = end_row['_group_position']
        current_window_id = end_row['window_id']

        # Calculate the start position within the group for this window
        start_position_in_group = end_position_in_group - window_size + 1

        # Get the global indices for the current group
        global_indices_for_group = group_indices[current_id]

        # Slice the global indices to get the indices for the current window
        window_global_indices = global_indices_for_group[start_position_in_group : end_position_in_group + 1]

        # Select the window data using the global indices
        window_data = df.iloc[window_global_indices].copy()

        # Assign the window ID and original ID to all rows in this window
        window_data['window_id'] = current_window_id
        # Keep track of the original ID if needed, avoid potential name clash
        window_data[f'{column_id}_original'] = current_id

        result_dataframes.append(window_data)

    # Concatenate all generated window DataFrames
    print("Concatenating results...")
    if result_dataframes: # Check if the list is not empty
        result_df = pd.concat(result_dataframes, ignore_index=True)
    else:
        # Should not happen if num_windows > 0, but as a safeguard
        print("Warning: No window dataframes were generated despite having potential window ends.")
        # Re-create empty DataFrame with expected columns
        expected_cols = list(df.columns) + ['window_id', f'{column_id}_original']
        expected_cols = [col for col in expected_cols if col not in ['_group_position', '_is_window_end']]
        result_df = pd.DataFrame(columns=expected_cols)

    # Remove temporary columns used for calculation
    print("Cleaning up temporary columns...")
    result_df = result_df.drop(columns=['_group_position', '_is_window_end'], errors='ignore')


    print(f"Rolling window processing complete: {num_windows} windows generated, total rows: {len(result_df)}.")

    return result_df
```
