### ISSUE TITLE
extract_features gives getattr() error when settings.from_columns param dict used.

### ISSUE THREAD

**Issue by ThomasMeli** [blue-yonder/tsfresh#797]
Hi all,

I'm having an issue getting extract_features to use the parameter dictionary extracted from tsfresh.feature_extraction.settings.from_columns.   It gives me an "getattr(): attribute name must be string" error.

Any solution that will let me just extract these features without going through the whole extract and filter process would be a win.  Although I imagine just having this work from the proposed method below would also be a goal for the API.

Mac OSX 11.1
TSfresh version: '0.17.0'
The data is not open without registration, so I can't share it here.

**I used the tsfresh.feature_extraction.settings.from_columns method to extract**

```
kind_to_fc_parameters = tsfresh.feature_extraction.settings.from_columns(analyzer.X.loc[:,features_intersection])
kind_to_fc_parameters
```

**To extract the following dictionary:**
```
tsfresh_param_dict = {'feature_17': {'median': None},
 'feature_23': {'mean': None},
 'feature_8': {'minimum': None},
 'feature_9': {'minimum': None},
 'feature_34': {'sum_values': None},
 'feature_11': {'sum_values': None},
 'feature_28': {'maximum': None},
 'feature_24': {'mean': None},
 'feature_53': {'sum_values': None},
 'feature_77': {'minimum': None},
 'feature_13': {'sum_values': None},
 'feature_122': {'minimum': None},
 'feature_21': {'sum_values': None},
 'feature_22': {'minimum': None},
 'feature_5': {'minimum': None},
 'feature_33': {'median': None},
 'feature_27': {'sum_values': None},
 'feature_69': {'maximum': None},
 'feature_1': {'sum_values': None},
 'feature_124': {'minimum': None},
 'feature_37': {'median': None},
 'feature_93': {'minimum': None},
 'feature_38': {'minimum': None},
 'feature_86': {'minimum': None},
 'feature_40': {'mean': None},
 'feature_78': {'sum_values': None},
 'feature_60': {'sum_values': None},
 'feature_18': {'sum_values': None},
 'feature_26': {'median': None},
 'feature_39': {'median': None},
 'feature_87': {'sum_values': None},
 'feature_3': {'maximum': None},
 'feature_42': {'sum_values': None},
 'feature_61': {'maximum': None},
 'feature_31': {'sum_values': None},
 'feature_32': {'median': None},
 'feature_6': {'minimum': None},
 'feature_92': {'median': None},
 'feature_43': {'maximum': None},
 'feature_72': {'mean': None},
 'feature_128': {'median': None},
 'feature_7': {'minimum': None},
 'feature_36': {'sum_values': None},
 'feature_120': {'mean': None},
 'feature_35': {'mean': None},
 'feature_74': {'mean': None},
 'feature_12': {'median': None},
 'feature_126': {'maximum': None}}
```

**When I use the following:**
```
extracted_features = extract_features(X, y,
                                        column_id="index",
                                        chunksize = 10000, 
                                        n_jobs = 3,
                                        kind_to_fc_parameters = tsfresh_param_dict)
                                      
```

**I get the following error:**
```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/thomasmeli/anaconda3/envs/jane/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/thomasmeli/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 43, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/Users/thomasmeli/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/utilities/distribution.py", line 42, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/Users/thomasmeli/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 328, in _do_extraction_on_chunk
    return list(_f())
  File "/Users/thomasmeli/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py", line 293, in _f
    func = getattr(feature_calculators, function_name)
TypeError: getattr(): attribute name must be string
"""

TypeError                                 Traceback (most recent call last)
<ipython-input-12-ac81f4a500fa> in <module>
     15                                         chunksize = 10000,
     16                                         n_jobs = 3,
---> 17                                         kind_to_fc_parameters = tsfresh_param_dict)
     18 
     19     X = extracted_features

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor, pivot)
    159                                 kind_to_fc_parameters=kind_to_fc_parameters,
    160                                 distributor=distributor,
--> 161                                 pivot=pivot)
    162 
    163         # Impute the result if requested

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py in _do_extraction(df, column_id, column_value, column_kind, column_sort, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, show_warnings, distributor, pivot)
    253     result = distributor.map_reduce(_do_extraction_on_chunk, data=data,
    254                                     chunk_size=chunk_size,
--> 255                                     function_kwargs=kwargs)
    256 
    257     if not pivot:

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/utilities/distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    211             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    212 
--> 213         result = list(itertools.chain.from_iterable(result))
    214 
    215         self.close()

~/anaconda3/envs/jane/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1164 
   1165         try:
-> 1166             for obj in iterable:
   1167                 yield obj
   1168                 # Update and possibly print the progressbar.

~/anaconda3/envs/jane/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

~/anaconda3/envs/jane/lib/python3.7/multiprocessing/pool.py in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/utilities/distribution.py in _function_with_partly_reduce()
     41     kwargs = kwargs or {}
     42     results = (map_function(chunk, **kwargs) for chunk in chunk_list)
---> 43     results = list(itertools.chain.from_iterable(results))
     44     return results
     45 

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/utilities/distribution.py in <genexpr>()
     40     """
     41     kwargs = kwargs or {}
---> 42     results = (map_function(chunk, **kwargs) for chunk in chunk_list)
     43     results = list(itertools.chain.from_iterable(results))
     44     return results

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py in _do_extraction_on_chunk()
    326                 yield (sample_id, feature_name, item)
    327 
--> 328     return list(_f())

~/anaconda3/envs/jane/lib/python3.7/site-packages/tsfresh/feature_extraction/extraction.py in _f()
    291     def _f():
    292         for function_name, parameter_list in fc_parameters.items():
--> 293             func = getattr(feature_calculators, function_name)
    294 
    295             # If the function uses the index, pass is at as a pandas Series.

TypeError: getattr(): attribute name must be string
```

**Comment by nils-braun** [comment]
Hi @ThomasMeli!
Thanks for the bug report :-)
That does definitely look strange - and honestly I do not really understand it (because we actually test for exactly this use case in our unittests: extracting the columns and then using those again as input).

As you can probably not share your data, I have tried to reproduce it:

```python


import pandas as pd
from tsfresh import extract_features

kind_to_fc_parameters = {
    "feature_1": {"sum_values": None},
    "feature_11": {"sum_values": None},
    "feature_12": {"median": None},
    "feature_120": {"mean": None},
    "feature_122": {"minimum": None},
    "feature_124": {"minimum": None},
    "feature_126": {"maximum": None},
    "feature_128": {"median": None},
    "feature_13": {"sum_values": None},
    "feature_17": {"median": None},
    "feature_18": {"sum_values": None},
    "feature_21": {"sum_values": None},
    "feature_22": {"minimum": None},
    "feature_23": {"mean": None},
    "feature_24": {"mean": None},
    "feature_26": {"median": None},
    "feature_27": {"sum_values": None},
    "feature_28": {"maximum": None},
    "feature_3": {"maximum": None},
    "feature_31": {"sum_values": None},
    "feature_32": {"median": None},
    "feature_33": {"median": None},
    "feature_34": {"sum_values": None},
    "feature_35": {"mean": None},
    "feature_36": {"sum_values": None},
    "feature_37": {"median": None},
    "feature_38": {"minimum": None},
    "feature_39": {"median": None},
    "feature_40": {"mean": None},
    "feature_42": {"sum_values": None},
    "feature_43": {"maximum": None},
    "feature_5": {"minimum": None},
    "feature_53": {"sum_values": None},
    "feature_6": {"minimum": None},
    "feature_60": {"sum_values": None},
    "feature_61": {"maximum": None},
    "feature_69": {"maximum": None},
    "feature_7": {"minimum": None},
    "feature_72": {"mean": None},
    "feature_74": {"mean": None},
    "feature_77": {"minimum": None},
    "feature_78": {"sum_values": None},
    "feature_8": {"minimum": None},
    "feature_86": {"minimum": None},
    "feature_87": {"sum_values": None},
    "feature_9": {"minimum": None},
    "feature_92": {"median": None},
    "feature_93": {"minimum": None},
}

df = pd.DataFrame({
    f"feature_{i}": [1, 2, 3]
    for i in range(1, 130)
})
df["id"] = 1

print(extract_features(df, column_id="id", kind_to_fc_parameters=kind_to_fc_parameters))
```

**Comment by nils-braun** [comment]
Oh sorry, @ThomasMeli  - looking back at your post I see something different: `extract_features` should not get the `y` vector as input. You actually set the `default_fc_parameters` (which is the parameter after `X`) to `y` - which will definitely lead to some strange problems :-)
Just remove the `y` in the second call and that should probably solve it

**Comment by ThomasMeli** [comment]
That fixed it Nils!  Thank you so much for the incredibly fast response!  So impressed by your quickness and thoroughness.  Thank you!
