### ISSUE TITLE
FileNotFoundError when using "extract_features" function 

### ISSUE THREAD

**Issue by benejo123** [blue-yonder/tsfresh#971]
Hi there, 
Thanks a lot for all your work in developing this package! I would love to use it, but run into problems already when implementing the "[Quick Start Code](https://tsfresh.readthedocs.io/en/latest/text/quick_start.html)" you provide in the docs. 

When running the following code: 

```
`from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
    load_robot_execution_failures
download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()

extract more then 1200 features
from tsfresh import extract_features

extracted_features = extract_features(timeseries, column_id="id", column_sort="time")`
```

I get repetitively this error message (it never stops coming up): 

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/benediktjordan/Desktop/MasterThesis_Iteration01/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/benediktjordan/Desktop/MasterThesis_Iteration01/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/runpy.py", line 287, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/miniconda3/envs/py39_x86/lib/python3.9/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/benediktjordan/Desktop/MasterThesis_Iteration01/<input>'
```

**Background details:**
Python version: 3.9.13
tsfresh version: 0.19.0
tsfresh was installed using pip 
I am using an MacBook Pro including a M1 chip. Since tsfresh isn´t compatible with Apple Silicon, I am using a x86 Python version (used [this guide to create a x86 Python architecture](https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12)) 

Does anybody have a solution idea for this problem? 
That would be fantastic!

**Comment by numinato** [comment]
Hi @benejo123,

I have encountered the same problem, which appears an issue with multiprocessing. Running the code as follows should solve the issue:

```
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
        load_robot_execution_failures
from tsfresh import extract_features

if __name__ == "__main__":
    download_robot_execution_failures()
    timeseries, y = load_robot_execution_failures()
    extracted_features = extract_features(timeseries, column_id="id",
                                          column_sort="time") 
```

**Comment by kempa-liehr** [comment]
@numinato, thanks for your feedback on solving the problem.
