### ISSUE TITLE
Custom features not considered when also `kind_to_fc_parameters` is supplied.

### ISSUE THREAD

**Issue by AlexMV12** [blue-yonder/tsfresh#998]
**The problem**:
Custom features are not seen when also `kind_to_fc_parameters` is supplied. I would like to use `kind_to_fc_parameters` because I need only certain features for my time-series, of which one is a custom-defined one.
If I don't include `kind_to_fc_parameters`, the extract_features works correctly.

MWE:

```python
from tsfresh import extract_features
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

from tsfresh.feature_extraction import ComprehensiveFCParameters, MinimalFCParameters
from tsfresh.feature_extraction.feature_calculators import set_property

import pandas as pd

# Create data.
data = pd.DataFrame({'col_A': [0, 1, 2, 3], 'id': [0, 0, 0, 0]})

# Create a function for a custom feature.
@set_property("fctype", "simple")
def f(x):
    return 1

# Include the custom feature.
settings = MinimalFCParameters()
settings[f] = None

# The custom feature will be extracted along the others.
extracted_features = extract_features(data,  default_fc_parameters=settings, column_id='id')


# Create a kind_to_fc dictionary, to only extract this feature from col_A.
kind_to_fc_settings = {
    "col_A": {'f': None }
}

# Include both the default_fc_parameters AND the kind_to_fc_parameters dicts.
extracted_features = extract_features(data, default_fc_parameters=settings,
                                      kind_to_fc_parameters=kind_to_fc_settings,
                                      column_id='id')
```

This will give you this error:
```
Feature Extraction:   0%|                                                                                                                                              | 0/1 [00:00<?, ?it/s]

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/ale/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/utilities/distribution.py", line 43, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/home/ale/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/utilities/distribution.py", line 42, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/home/ale/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/feature_extraction/extraction.py", line 386, in _do_extraction_on_chunk
    return list(_f())
  File "/home/ale/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/feature_extraction/extraction.py", line 343, in _f
    func = getattr(feature_calculators, f_or_function_name)
AttributeError: module 'tsfresh.feature_extraction.feature_calculators' has no attribute 'f'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[13], line 8
      2 settings[f] = None
      4 kind_to_fc_settings = {
      5     "col_A": {'f': None}
      6 }
----> 8 extracted_features = extract_features(data, default_fc_parameters=settings,
      9                                       kind_to_fc_parameters=kind_to_fc_settings,
     10                                       column_id='id')

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/feature_extraction/extraction.py:164, in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor, pivot)
    161 else:
    162     warnings.simplefilter("default")
--> 164 result = _do_extraction(
    165     df=timeseries_container,
    166     column_id=column_id,
    167     column_value=column_value,
    168     column_kind=column_kind,
    169     column_sort=column_sort,
    170     n_jobs=n_jobs,
    171     chunk_size=chunksize,
    172     disable_progressbar=disable_progressbar,
    173     show_warnings=show_warnings,
    174     default_fc_parameters=default_fc_parameters,
    175     kind_to_fc_parameters=kind_to_fc_parameters,
    176     distributor=distributor,
    177     pivot=pivot,
    178 )
    180 # Impute the result if requested
    181 if impute_function is not None:

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/feature_extraction/extraction.py:294, in _do_extraction(df, column_id, column_value, column_kind, column_sort, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, show_warnings, distributor, pivot)
    286     raise ValueError("the passed distributor is not an DistributorBaseClass object")
    288 kwargs = dict(
    289     default_fc_parameters=default_fc_parameters,
    290     kind_to_fc_parameters=kind_to_fc_parameters,
    291     show_warnings=show_warnings,
    292 )
--> 294 result = distributor.map_reduce(
    295     _do_extraction_on_chunk,
    296     data=data,
    297     chunk_size=chunk_size,
    298     function_kwargs=kwargs,
    299 )
    301 if not pivot:
    302     return result

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/utilities/distribution.py:241, in IterableDistributorBaseClass.map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    234 else:
    235     result = (
    236         self.distribute(
    237             _function_with_partly_reduce, chunk_generator, map_kwargs
    238         ),
    239     )
--> 241 result = list(itertools.chain.from_iterable(result))
    243 self.close()
    245 return result

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tqdm/std.py:1195, in tqdm.__iter__(self)
   1192 time = self._time
   1194 try:
-> 1195     for obj in iterable:
   1196         yield obj
   1197         # Update and possibly print the progressbar.
   1198         # Note: does not call self.update(1) for speed optimisation.

File /usr/lib/python3.10/multiprocessing/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

File /usr/lib/python3.10/multiprocessing/pool.py:125, in worker()
    123 job, i, func, args, kwds = task
    124 try:
--> 125     result = (True, func(*args, **kwds))
    126 except Exception as e:
    127     if wrap_exception and func is not _helper_reraises_exception:

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/utilities/distribution.py:43, in _function_with_partly_reduce()
     41 kwargs = kwargs or {}
     42 results = (map_function(chunk, **kwargs) for chunk in chunk_list)
---> 43 results = list(itertools.chain.from_iterable(results))
     44 return results

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/utilities/distribution.py:42, in <genexpr>()
     25 """
     26 Small helper function to call a function (map_function)
     27 on a list of data chunks (chunk_list) and convert the results into
   (...)
     39 :rtype: list
     40 """
     41 kwargs = kwargs or {}
---> 42 results = (map_function(chunk, **kwargs) for chunk in chunk_list)
     43 results = list(itertools.chain.from_iterable(results))
     44 return results

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/feature_extraction/extraction.py:386, in _do_extraction_on_chunk()
    383 else:
    384     warnings.simplefilter("default")
--> 386 return list(_f())

File ~/Venvs/TSFresh_Test/lib/python3.10/site-packages/tsfresh/feature_extraction/extraction.py:343, in _f()
    341     func = f_or_function_name
    342 else:
--> 343     func = getattr(feature_calculators, f_or_function_name)
    345 # If the function uses the index, pass is at as a pandas Series.
    346 # Otherwise, convert to numpy array
    347 if getattr(func, "input", None) == "pd.Series":
    348     # If it has a required index type, check that the data has the right index type.

AttributeError: module 'tsfresh.feature_extraction.feature_calculators' has no attribute 'f'
```

**Anything else we need to know?**:

**Environment**:

- Python version: 3.10.9
- Operating System: ArchLinux
- tsfresh version:  tsfresh==0.20.0
- Install method (conda, pip, source): pip

**Comment by nils-braun** [comment]
Hi @AlexMV12 ! Thanks for the MWE (that really helps in debugging!)
I thank your `kind_to_fc_settings` is slightly not waht you want: as `f` is a custom function, you want to pass it as the function itself (not as the name). If you switch its definition to
```python
kind_to_fc_settings = {
    "col_A": {f: None }
}
```
I get the correct result:
```
   col_A__f
0       1.0
```

**Comment by AlexMV12** [comment]
Hello @nils-braun ,

Thanks! This solved my problem. 

Moreover, I have seen that I don't even need to put `f` in the minimal_fc_parameters. :) I'll close this, thanks again.
